version: '3.1'

volumes:
  mysqldata:
  zabbixdata:
  grafanadata:

networks:
  network-zabbix:
    driver: bridge

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    networks:
      - network-zabbix
    ports:
      - '3306:3306'
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=MYPASSWORD
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=MYPASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=no

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:ubuntu-5.4.5
    networks:
      - network-zabbix
    links:
      - mysql
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - zabbixdata:/usr/lib/zabbix
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=MYPASSWORD
      - ZBX_VALUECACHESIZE=1024M
      - ZBX_TIMEOUT=15
      - ZBX_LOGSLOWQUERIES=3000
      - ZBX_STATSALLOWEDIP=127.0.0.1
      - ZBX_STARTPOLLERS=50
      - ZBX_STARTHTTPPOLLERS=50
      - ZBX_STARTPREPROCESSORS=10
      - ZBX_STARTPOLLERSUNREACHABLE=10
      - ZBX_STARTPINGERS=50
      - ZBX_HOUSEKEEPINGFREQUENCY=6
      - ZBX_MAXHOUSEKEEPERDELETE=5000
      - ZBX_CACHESIZE=1024M
      - ZBX_HISTORYCACHESIZE=64M
      - ZBX_HISTORYINDEXCACHESIZE=64M
      - ZBX_TRENDCACHESIZE=64M
    depends_on:
      - mysql

  zabbix-front:
    container_name: zabbix-front
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-5.4.5
    networks:
      - network-zabbix
    links:
      - mysql
      - zabbix-server
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=mysql
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=MYPASSWORD
      - PHP_TZ=America/Sao_Paulo
      - ZBX_SERVER_NAME=Thorkks
    depends_on:
      - mysql
      - zabbix-server
    
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:8.2.6-ubuntu
    networks:
      - network-zabbix
    links:
      - mysql
      - zabbix-server
    ports:
      - '3000:3000'
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=alexanderzobnin-zabbix-app
      - GF_DEFAULT_INSTANCE_NAME=Thorkks
    volumes:
      - grafanadata:/var/lib/grafana
    depends_on:
      - mysql
      - zabbix-server

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:ubuntu-5.4.4
    user: root
    networks:
      - network-zabbix
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=zabbix-server
      - ZBX_SERVER_HOST=zabbix-server
